
/*
##############################################################
# This file is automatically generated.                      #
# Any change is temporary and will be overwritten eventually #
##############################################################
*/

  /// <reference path="affiliator.d.ts" />
  /// <reference path="bonus.namespace.d.ts" />
  /// <reference path="campaignTypes.d.ts" />
  /// <reference path="component.namespace.d.ts" />
  /// <reference path="coupon.namespace.d.ts" />
  /// <reference path="globaltypes.d.ts" />
  /// <reference path="navoverlay.types.d.ts" />
  /// <reference path="object.namespace.d.ts" />
  /// <reference path="offerista.namespace.d.ts" />
  /// <reference path="partner.types.d.ts" />
  /// <reference path="search.namespace.d.ts" />
  /// <reference path="shims-tsx.d.ts" />
  /// <reference path="shims-vue.d.ts" />
  /// <reference path="shims.images.d.ts" />